@ECHO OFF

:: Set the autorun parameters.
SET APP_IS_AUTORUN_MODE=TRUE
SET APP_INPUT_WORKBOOK_FILE_PATH=H:\INPUT_WORKBOOK.xlsx
SET APP_QUERY_FILE_PATH=H:\QUERY.sql
SET APP_OUTPUT_WORKBOOK_FILE_PATH=H:\OUTPUT_WORKBOOK.xlsx

:: Run the main project workbook.
CALL "SQLParser.xlsm"
